services:
  - type: web
    name: student-manager-web
    env: python
    branch: main
    plan: free
    region: oregon # MUST be the same region as your database
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: student-manager-db
          property: internalConnectionString
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false